export const PATHS = {
    AUTH: "auth",
    SECRET_AUTH: "auth/secret",
    RESET_PASSWORD: "reset-password",
    HOME: "",
    RECORD: "record",
    FAQ: "faq",
    SUPPORT: "support",
    ADMIN: "admin",
    PROFILE: "profile",
    USERS: "users",
    USER: "user",
    BOT_OWNERS: "botowners",
    WITHDRAWALS: "withdrawals",
    PERMANENT_FIELDS: "permanent-fields",
    EMPLOYEES: "employees",
    EMPLOYEE: "employee",
    NOTIFICATIONS: "notifications",
};
